name: 'generate-chrome-extension'
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: setup node 10 environment
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: install
        run: npm install --ignore-scripts
      - name: build
        run: npm run build:production
      - name: unit test
        run: npm run test
      - name: prepare artifact
        if: startsWith(github.ref, 'refs/tags/v')
        run: rsync -av --progress . lib --exclude node_modules --exclude lib --exclude .github --exclude .git --exclude src
      - name: upload artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: lib
  npm:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: lib
          path: lib
      - name: npm publish
        run: |
          cd lib
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
